#!/usr/bin/env python3
"""Render project-specific standards from the standards/ single source.

standards/*.md are the canonical, placeholder-parameterized sources; rendered
copies are generated, never hand-maintained. Substitution replaces every
`{{PLACEHOLDER}}` with the value the consumer supplies in a JSON config, and
the placeholder vocabulary is closed: a source using an unregistered token, or
malformed double-brace syntax, fails loudly. Single-brace text (URL templates
like `/users/{id}`, JSON examples) passes through untouched.

Shared report templates live under standards/templates/ and serve several
skills at once: each is authored once and copied verbatim —
prefixed with a generated-do-not-edit header — into every consuming skill's
references/ directory, so the conformance suite's template-containment rule
holds without hand-maintained twins. Copies are committed; --check fails on a
copy that is missing or has drifted from its source.

Usage:
    python3 scripts/render_standards.py --check
        # validate placeholder integrity of every source and shared-template
        # copy freshness (run by CI)
    python3 scripts/render_standards.py --render-shared
        # regenerate the shared-template copies inside this repository
    python3 scripts/render_standards.py --config cfg.json --out DIR [--only a,b]
        # render sources into DIR; --only limits to named standards
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import NoReturn

DEFAULT_ROOT = Path(__file__).resolve().parent.parent

# The closed placeholder vocabulary. A new placeholder is added here first;
# sources may then use it and configs must then supply it.
PLACEHOLDERS = {
    "PROJECT_NAME": "the consuming project's name",
    "TECH_STACK": "the project's primary language/framework stack",
    "ARCHITECTURE_TYPE": "the project's architecture pattern",
}

WELL_FORMED = re.compile(r"\{\{([A-Z][A-Z0-9_]*)\}\}")

# Shared report templates: source file under standards/templates/
# mapped to every skill-side copy generated from it. A new consumer is added
# here first; --render-shared then writes its copy and --check enforces it.
SHARED_TEMPLATES: dict[str, tuple[str, ...]] = {
    "review-report.template.md": (
        "skills/awf-review-code/references/review-report.template.md",
        "skills/awf-review-security/references/review-report.template.md",
    ),
    "validation-report.template.md": (
        "skills/awf-deliver-validate/references/validation-report.template.md",
        "skills/awf-implement-validate/references/validation-report.template.md",
        "skills/awf-plan-validate/references/validation-report.template.md",
        "skills/awf-review-validate/references/validation-report.template.md",
    ),
}

SHARED_DIR = "standards/templates"

SKILL_FILES = "skills/*/**/*.md"

SHARED_MARKER = "<!-- GENERATED TEMPLATE COPY"

# Characters a hand-copied file may carry before the marker: a byte-order mark
# (written by some editors) and ordinary whitespace. Spelled as an escape so the
# BOM stays visible to reviewers and survives editing.
MARKER_LEAD = "\ufeff \t\r\n"

SHARED_HEADER = (
    SHARED_MARKER
    + """ - do not edit this file; edit the source and regenerate.
Source: {source}
Regenerate: python3 scripts/render_standards.py --render-shared
This notice governs only the template copy itself: artifacts scaffolded from it
are filled by their step as usual. -->

"""
)


def fail(message: str) -> NoReturn:
    sys.exit(f"render-standards: {message}")


def source_paths(root: Path) -> list[Path]:
    standards = root / "standards"
    if not standards.is_dir():
        fail(f"{standards}: not a directory")
    paths = sorted(p for p in standards.glob("*.md") if p.name != "README.md")
    if not paths:
        fail(f"no sources match {standards}/*.md")
    return paths


def integrity_problems(path: Path, root: Path) -> list[str]:
    """Placeholder-integrity findings for one source file."""
    at = path.relative_to(root).as_posix()
    text = path.read_text(encoding="utf-8")
    problems = []
    known = ", ".join("{{" + name + "}}" for name in sorted(PLACEHOLDERS))
    for token in dict.fromkeys(WELL_FORMED.findall(text)):
        if token not in PLACEHOLDERS:
            problems.append(
                f'{at}: unknown placeholder "{{{{{token}}}}}" (registered: {known})'
            )
    # With well-formed occurrences removed, any surviving double brace is
    # malformed syntax: an unclosed `{{TOKEN}`, a lowercase token, etc.
    stripped = WELL_FORMED.sub("", text)
    for lineno, line in enumerate(stripped.splitlines(), start=1):
        if "{{" in line or "}}" in line:
            problems.append(
                f"{at}:{lineno}: malformed double-brace placeholder syntax"
            )
    return problems


def shared_copy_text(root: Path, name: str) -> str:
    header = SHARED_HEADER.format(source=f"{SHARED_DIR}/{name}")
    return header + (root / SHARED_DIR / name).read_text(encoding="utf-8")


def shared_source_problems(root: Path) -> list[str]:
    """Integrity findings for the shared-template sources themselves."""
    problems = []
    for name in sorted(SHARED_TEMPLATES):
        rel = f"{SHARED_DIR}/{name}"
        source = root / SHARED_DIR / name
        if not source.is_file():
            problems.append(f"{rel}: registered shared template not found")
            continue
        # Copies are committed verbatim into skill directories where no config
        # exists to resolve anything — placeholder syntax can never render.
        for lineno, line in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
            if "{{" in line or "}}" in line:
                problems.append(
                    f"{rel}:{lineno}: shared templates are copied verbatim, "
                    "never rendered — double-brace placeholder syntax is not allowed"
                )
    return problems


def shared_copy_problems(root: Path) -> list[str]:
    """Drift findings for the generated copies: each must exist and match its
    source exactly, header included."""
    problems = []
    for name, copies in sorted(SHARED_TEMPLATES.items()):
        if not (root / SHARED_DIR / name).is_file():
            continue  # the missing source is shared_source_problems' finding
        expected = shared_copy_text(root, name)
        for copy in copies:
            target = root / copy
            if not target.is_file():
                problems.append(f"{copy}: generated copy missing — run --render-shared")
            elif target.read_text(encoding="utf-8") != expected:
                problems.append(
                    f"{copy}: drifted from {SHARED_DIR}/{name} — run --render-shared"
                )
    return problems


def unregistered_copy_problems(root: Path) -> list[str]:
    """Findings for header-carrying generated copies the registry does not own.
    A skill that hand-copies a shared template — header and all — from a
    neighboring skill is never re-rendered and never drift-checked, so it
    diverges from its source silently. A copy whose header was stripped is
    indistinguishable from an authored file and stays out of scope."""
    registered = {copy for copies in SHARED_TEMPLATES.values() for copy in copies}
    problems = []
    for path in sorted(root.glob(SKILL_FILES)):
        rel = path.relative_to(root).as_posix()
        if rel in registered:
            continue
        if path.read_text(encoding="utf-8").lstrip(MARKER_LEAD).startswith(SHARED_MARKER):
            problems.append(
                f"{rel}: carries the generated-copy header but no SHARED_TEMPLATES "
                "entry owns it — register the copy or it drifts unnoticed"
            )
    return problems


def render_shared(root: Path) -> int:
    problems = shared_source_problems(root)
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        fail("shared templates failed integrity; not rendering")
    written = 0
    for name, copies in sorted(SHARED_TEMPLATES.items()):
        text = shared_copy_text(root, name)
        for copy in copies:
            target = root / copy
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            print(f"rendered {target}")
            written += 1
    print(f"standards: {written} shared-template cop(y/ies) rendered")
    return 0


def check(root: Path) -> int:
    problems = []
    for path in source_paths(root):
        problems += integrity_problems(path, root)
    problems += shared_source_problems(root)
    problems += shared_copy_problems(root)
    problems += unregistered_copy_problems(root)
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        print(f"standards: {len(problems)} problem(s)", file=sys.stderr)
        return 1
    # Prove a full render resolves everything: substitute sample values and
    # assert no residue. Guards the check itself against regex drift.
    sample = {name: f"<{name}>" for name in PLACEHOLDERS}
    for path in source_paths(root):
        rendered = substitute(path.read_text(encoding="utf-8"), sample)
        if "{{" in rendered or "}}" in rendered:
            fail(f"{path.relative_to(root).as_posix()}: unresolved placeholder after render")
    copies = sum(len(targets) for targets in SHARED_TEMPLATES.values())
    print(
        f"standards: {len(source_paths(root))} source(s) clean, "
        f"{copies} shared-template cop(y/ies) fresh"
    )
    return 0


def load_config(path: Path) -> dict[str, str]:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        fail(f"{path}: {error.strerror or error}")
    except json.JSONDecodeError as error:
        fail(f"{path}: invalid JSON — {error}")
    if not isinstance(raw, dict):
        fail(f"{path}: config must be a JSON object of placeholder → value")
    known = ", ".join(sorted(PLACEHOLDERS))
    for key, value in raw.items():
        if key not in PLACEHOLDERS:
            fail(f'{path}: unknown placeholder "{key}" (registered: {known})')
        if not isinstance(value, str) or not value.strip():
            fail(f'{path}: "{key}" must be a non-empty string')
    return {key: value.strip() for key, value in raw.items()}


def substitute(text: str, values: dict[str, str]) -> str:
    return WELL_FORMED.sub(lambda m: values.get(m.group(1), m.group(0)), text)


def render(root: Path, config: dict[str, str], out: Path, only: list[str] | None) -> int:
    paths = source_paths(root)
    if only is not None:
        by_name = {p.stem: p for p in paths}
        missing = sorted(set(only) - set(by_name))
        if missing:
            available = ", ".join(sorted(by_name))
            fail(f"unknown standard(s): {', '.join(missing)} (available: {available})")
        paths = [by_name[name] for name in sorted(set(only))]

    problems = []
    for path in paths:
        problems += integrity_problems(path, root)
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        fail("sources failed placeholder integrity; not rendering")

    needed = {
        token
        for path in paths
        for token in WELL_FORMED.findall(path.read_text(encoding="utf-8"))
    }
    unsupplied = sorted(needed - set(config))
    if unsupplied:
        fail(f"config missing value(s) for: {', '.join(unsupplied)}")

    out.mkdir(parents=True, exist_ok=True)
    for path in paths:
        target = out / path.name
        target.write_text(
            substitute(path.read_text(encoding="utf-8"), config), encoding="utf-8"
        )
        print(f"rendered {target}")
    print(f"standards: {len(paths)} file(s) rendered to {out}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate placeholder integrity of every source and shared-template "
        "copy freshness instead of rendering",
    )
    parser.add_argument(
        "--render-shared",
        action="store_true",
        help="regenerate the shared-template copies inside this repository",
    )
    parser.add_argument("--config", type=Path, help="JSON file of placeholder → value")
    parser.add_argument("--out", type=Path, help="directory to write rendered files to")
    parser.add_argument(
        "--only",
        help="comma-separated standard names to render (default: all)",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help="repository root to operate on (default: this script's repository)",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()

    if args.render_shared:
        if args.check or args.config or args.out or args.only:
            fail("--render-shared takes no --check/--config/--out/--only")
        return render_shared(root)
    if args.check:
        if args.config or args.out or args.only:
            fail("--check takes no --config/--out/--only")
        return check(root)
    if not args.config or not args.out:
        fail("rendering needs --config and --out (or use --check)")
    only = None
    if args.only is not None:
        only = [name.strip() for name in args.only.split(",")]
        if "" in only:
            fail("--only contains an empty standard name (check for stray commas)")
    return render(root, load_config(args.config), args.out.resolve(), only)


if __name__ == "__main__":
    sys.exit(main())
